services:
  l4d2-server:
    image: l4d2-server:latest
    container_name: l4d2-server
    restart: unless-stopped
    network_mode: host
    volumes:
      - addons:/home/steam/l4d2server/left4dead2/addons
      - cfg:/home/steam/l4d2server/left4dead2/cfg
      - ./data/motd.txt:/home/steam/l4d2server/left4dead2/motd.txt
      - ./data/host.txt:/home/steam/l4d2server/left4dead2/host.txt

volumes:
    addons: null
    cfg: null
