services:
  l4d2-server:
    image: l4d2-server:latest
    container_name: l4d2-server
    restart: unless-stopped
    network_mode: host
    environment:
      - SERVERPORT=${PANEL_APP_PORT_HTTP}
    user: steam
    volumes:
      - scripts:/home/steam/l4d2server/left4dead2/scripts
      - addons:/home/steam/l4d2server/left4dead2/addons
      - cfg:/home/steam/l4d2server/left4dead2/cfg
      - ems:/home/steam/l4d2server/left4dead2/ems
      - ./data/motd.txt:/home/steam/l4d2server/left4dead2/motd.txt
      - ./data/host.txt:/home/steam/l4d2server/left4dead2/host.txt
      - ./data/run.sh:/home/steam/l4d2server/run.sh

volumes:
    scripts:
      driver: local
      driver_opts:
        o: bind
        type: none
        device: ./data/scripts
    addons:
      driver: local
      driver_opts:
        o: bind
        type: none
        device: ./data/addons
    cfg:
      driver: local
      driver_opts:
        o: bind
        type: none
        device: ./data/cfg
    ems:
      driver: local
      driver_opts:
        o: bind
        type: none
        device: ./data/ems
