services:
  l4d2-server:
    image: l4d2-server:latest
    container_name: l4d2-server
    restart: unless-stopped
    network_mode: host
    volumes:
      - addons:/home/steam/l4d2server/left4dead2/addons:rw
      - cfg:/home/steam/l4d2server/left4dead2/cfg:rw
      - ./data/host.txt:/home/steam/l4d2server/left4dead2/host.txt
      - ./data/motd.txt:/home/steam/l4d2server/left4dead2/motd.txt
volumes:
    addons: null
    cfg: null
