services:
  openwrt:
    image: zzsrv/openwrt
    container_name: openwrt
    restart: always
    networks: 
      - 1panel-network
    privileged: true
    command: /sbin/init

networks:
  1panel-network:
    external: true
