services:
  openwrt:
    image: zzsrv/openwrt
    container_name: openwrt
    restart: always
    networks: 
      - 1panel-network
    privileged: true
    command: /sbin/init
    ports:
      - ${PANEL_APP_PORT_HTTP}:80
networks:
  1panel-network:
    external: true
