services:
  openwrt:
    image: zzsrv/openwrt
    container_name: openwrt
    restart: always
    networks: 
      - macnet # 使用已有的macnet网络
    privileged: true
    command: /sbin/init

networks:
  macnet: 
    ipv4_address: 192.168.0.2
    external: true # 指定macnet为外部网络
