services:
  qbittorrent:
    image: superng6/qbittorrentee
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    environment:
      - PUID=0
      - PGID=0
      - UMASK_SET=022
      - TZ=${TIME_ZONE}
      - WEBUI_PORT=${PANEL_APP_PORT_HTTP}
      - TORRENTING_PORT=${PANEL_TORRENTING_PORT}
    ports:
      - ${PANEL_TORRENTING_PORT}:6881
      - ${PANEL_TORRENTING_PORT}:6881/udp
      - ${PANEL_APP_PORT_HTTP}:8080
    volumes:
      - ./config:/config
      - ./data:/downloads
    labels:
      createdBy: "Apps"
networks:
  1panel-network:
    external: true

