server:
  # debug release test
  model: release
  port: 18888
  cors: true
  tls:
    enable: false
    key-file: ./default.key
    cert-file: ./default.pem
jwt:
  # jwt key，不设置默认使用随机字符串
  key: 
  # 过期时间单位分钟
  expire-time: 720
  # refreshToken过期时间单位分钟
  refresh-token-expire-time: 4320
# 资源密码aes加密key
aes:
  key: 1111111111111111
mysql:
  host: localhost:3306
  username: root
  password: 111049
  db-name: mayfly-go
  config: charset=utf8&loc=Local&parseTime=true
  max-idle-conns: 5
sqlite:
	# sqlite数据文件位置（需要到获取初始化的sqlite数据文件放置到自定义位置）
  path: ./mayfly-go.sqlite
  max-idle-conns: 5
log:
   # 日志等级, debug, info, warn, error
  level: info
  # 日志格式类型, text/json
  type: text
  # 是否记录方法调用栈信息
  add-source: false
  # file:
  #   path: ./
  #   name: mayfly-go.log