version: '3.8'

services:
  gpt-sovits:
    image: breakstring/gpt-sovits:latest
    container_name: ${CONTAINER_NAME}
    networks:
      - 1panel-network
    environment:
        - is_half=False
        - is_share=False
        #i18
        - LANG=zh_CN.UTF-8
        - LC_ALL=zh_CN.UTF-8
    volumes:
      - ./data/output:/workspace/output
      - ./data/logs:/workspace/logs
      - ./data/SoVITS_weights:/workspace/SoVITS_weights
      - ./data/reference:/workspace/reference
      - ./data/GPT_weights:/workspace/GPT_weights
    working_dir: /workspace
    ports:
      - "${PANEL_SOVITS_PORT_API}:9880"
      - "${PANEL_SOVITS_PORT_3}:9871"
      - "${PANEL_SOVITS_PORT_2}:9872"
      - "${PANEL_SOVITS_PORT_1}:9873"
      - "${PANEL_APP_PORT_HTTP}:9874"
    shm_size: ${SHM_SIZE}
    #deploy:
    #  resources:
    #    reservations:
    #      devices:
    #      - driver: nvidia
    #        count: "all"
    #        capabilities: [gpu]
    labels:
      createdBy: "Apps"
    runtime: nvidia
    stdin_open: true
    tty: true
    restart: always
    
networks:
  1panel-network:
    external: true
