services:
  meme-generator:
    image: ghcr.io/meetwq/meme-generator:main
    container_name: ${CONTAINER_NAME}
    networks:
      - 1panel-network
    restart: always
    ports:
      - ${PANEL_APP_PORT_HTTP}:2233
    volumes:
      - ./data:/data
    environment:
      - MEME_DIRS=["/data/memes"]
      - MEME_DISABLED_LIST=[]
      # - GIF_MAX_SIZE=10.0
      # - GIF_MAX_FRAMES=100
      - BAIDU_TRANS_APPID=${BAIDU_TRANS_APPID}
      - BAIDU_TRANS_APIKEY=${BAIDU_TRANS_APIKEY}
      - LOG_LEVEL=INFO

networks:
  1panel-network:
    external: true